;;; Text banner literals used in source code

(context 'Banners)

(setq copyright
      [text]// Copyright (C) 2019 Inkblot Software Limited[/text])

(setq autogenned
  [text]// THIS CODE IS 100% AUTOGENERATED, DO NOT EDIT EXCEPT EXPERIMENTALLY[/text])

