// THIS CODE IS 100% AUTOGENERATED, DO NOT EDIT EXCEPT EXPERIMENTALLY
// Copyright (C) 2019 Inkblot Software Limited

package com.inkblotsoftware.arraystore;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.LongBuffer;
import java.nio.FloatBuffer;
import java.nio.DoubleBuffer;

public class ByteStore implements AutoCloseable {
    Pointer _handle;
    
    public ByteStore (ASEnv env, String name) {
        _handle = CLibrary.INSTANCE.byteas_new (env._handle, name);
        // TODO better exception
        if (_handle == Pointer.NULL) {
            throw new RuntimeException ("Open failed");
        }
    }

    @Override public void close () {
        if (_handle == Pointer.NULL)
           return;
        CLibrary.INSTANCE.byteas_destroy (new PointerByReference (_handle));
        _handle = Pointer.NULL;
    }

    public ByteBuffer get (ASTxn txn, long key) {
        CLibrary.bytespan.ByValue sp =
            CLibrary.INSTANCE.byteas_get (_handle, txn._handle, UInt64.of(key));
        assert (sp != null);

        // TODO better exception
        if (sp.data == null)
            throw new RuntimeException ("Key not found");

        long numBytes = sp.size.longValue() * 1;
        ByteBuffer bb = sp.data.getPointer ()
                            .getByteBuffer (0, numBytes);
        return bb;
    }

    public void put (ASTxn txn, long key, byte[] data) {
        put (txn, key, ByteBuffer.wrap (data));
    }
    public void put (ASTxn txn, long key, ByteBuffer data) {
        int rc = CLibrary.INSTANCE.byteas_put (_handle, txn._handle,
                                               UInt64.of (key),
                                               data, Size_t.of (data.limit()));
        // TODO better exception
        if (rc != 0)
            throw new RuntimeException ("put() failed");
    }

    public boolean exists (ASTxn txn, long key) {
        int res = CLibrary.INSTANCE.byteas_exists (_handle, txn._handle,
                                                    UInt64.of (key));
        return res == 1;
    }
}

